import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Inter, Montserrat } from "next/font/google";
import Footer from "@/components/Footer/Footer";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={monsterrat.className}>
        <div className="flex flex-col justify-between min-h-screen">
          <div className="bg-gradient-to-b from-[#94B9FF] to-white">
            <Navbar />
            {children}
          </div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
